[build]
  command = "pip install -r requirements.txt"
  publish = "src"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"